dist: trusty

language: node_js

node_js:
  - "8.10.0"

install:
  - yarn

script:
  - npm run lint
  - npm test

after_script:
  - greenkeeper-lockfile-upload
  - if [ -n "${TRAVIS_TAG}" ]; then npm run github-release; fi
